apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1000;
    }

    http {
        server {
            listen 80;
            server_name localhost;

            location / {
                proxy_pass http://localhost:8080;
            }
        }
    }