apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-2-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: assignment-2-app
  template:
    metadata:
      labels:
        app: assignment-2-app
    spec:
      containers:
      - name: assignment-2-app
        image: rabiaqamar/assignment-2-app:latest
        ports:
        - containerPort: 80       # Make sure your app inside Docker listens on 80!
      imagePullSecrets:
        - name: docker-hub-secret