- name: Launch and Configure Staging instance
  hosts: localhost
  connection: local
  vars:
    instance_name: Staging_k8s
    key_name: assignment_2_app_key
    instance_type: t2.small
    security_group: assignment_2_app_sg
    image_id: ami-0866a3c8686eaeeba
    region: us-east-1
    ansible_ssh_private_key_file: assignment_2_app_key.pem

  tasks:
    - name: Launch T2 small instance on EC2
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ security_group }}"
        image_id: "{{ image_id }}"
        region: "{{ region }}"
        wait: yes
      register: staging_instance

    - name: Add new instance to host group
      add_host:
        hostname: "{{ staging_instance.instances[0].public_ip_address }}"
        groupname: ec2_staging

- name: Configure Staging instance
  hosts: ec2_staging
  vars:
    ansible_ssh_private_key_file: assignment_2_app_key.pem
    remote_ec2_user: ubuntu
  remote_user: "{{ remote_ec2_user }}"
  become: yes
  become_method: sudo

  tasks:
    - name: Add the Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt packages and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ remote_ec2_user }}"
        groups: docker
        append: yes

    - name: Install Python kubernetes module for ansible
      apt:
        name: python3-kubernetes
        state: present

    - name: Download Minikube
      shell: curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
      args:
        chdir: /home/ubuntu

    - name: Install Minikube
      shell: install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
      args:
        chdir: /home/ubuntu

    - name: Download kubectl
      shell: curl -LO https://dl.k8s.io/release/v1.32.0/bin/linux/amd64/kubectl
      args:
        chdir: /home/ubuntu

    - name: Install kubectl
      shell: install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      args:
        chdir: /home/ubuntu

    - name: Start Minikube
      shell: minikube start --extra-config=kubeadm.ignore-preflight-errors=NumCPU --force --cpus 1
      args:
        chdir: /home/ubuntu
